### ISSUE TITLE
An extra character was found

### ISSUE THREAD

**Issue by pavelkarinin** [odan/base62js#3]
The script throws an exception:

```
var str = "testValue";
var enc = $d.encodeBase62(str); // enc = 'T6LpT5PXR7Lb0'
var dec = $d.decodeBase62(enc); // 'An extra character was found'
```

it occurs if

`str.length == 9`

**Comment by odan** [comment]
Hi. I've reverted the last change (length check) and updated the unit tests. It should be fixed now.

**Comment by pavelkarinin** [comment]
Error here:
https://github.com/odan/base62js/blob/master/jquery.base62.js#L212

uncomment this part of the code:
```
		else if (length == 0)
		{
			break;
		}
```
